# 🔢 NumPy Homework — Class Grades Analyzer

**Estimated time:** ~1 hour

**Goal:** apply array creation, broadcasting, boolean masking, `axis`-aware aggregation,
sorting, and array manipulation on one connected scenario.

You are analyzing grades for **5 students** across **6 subjects**. Work through the tasks in
order — later tasks build on earlier ones. Add your code in the empty cell under each task.

In [1]:
import numpy as np
np.random.seed(42)

## Task 1 — Create the data (5 min)

Create a 5×6 array called `grades` of random integers between 40 and 100 (inclusive of 40,
exclusive of 101), representing grades for 5 students across 6 subjects.

Also create an array `students = np.array(['Layla', 'Omar', 'Sara', 'Kareem', 'Nour'])` and
`subjects = np.array(['Math', 'Science', 'English', 'History', 'Art', 'PE'])`.

In [2]:
# Your code here
grades = np.random.randint(40,101,size=(5,6))
students = np.array(['Layla', 'Omar', 'Sara', 'Kareem', 'Nour'])
subjects = np.array(['Math', 'Science', 'English', 'History', 'Art', 'PE'])

grades


array([[ 78,  91,  68,  54,  82,  47],
       [100,  60,  78,  97,  58,  62],
       [ 50,  50,  63,  92,  75,  79],
       [ 63,  42,  61,  92,  41,  63],
       [ 83,  69,  77,  41,  99,  60]], dtype=int32)

## Task 2 — Curve the grades (10 min)

Any grade **below 50** should get a **+5 curve**. Do this with boolean masking (no loops).
Print the updated `grades` array.

In [3]:
# Your code here
grades[grades<50] +=5
grades

array([[ 78,  91,  68,  54,  82,  52],
       [100,  60,  78,  97,  58,  62],
       [ 50,  50,  63,  92,  75,  79],
       [ 63,  47,  61,  92,  46,  63],
       [ 83,  69,  77,  46,  99,  60]], dtype=int32)

## Task 3 — Row and column statistics (10 min)

Using the correct `axis`, compute:
- `student_avg`: each student's average grade across all subjects
- `subject_avg`: each subject's average grade across all students

Print both, labeled with the corresponding names from `students` / `subjects`.

In [4]:
# Your code here
student_avg = grades.mean(axis=1) 
subject_avg = grades.mean(axis=0)

print(student_avg)
print(subject_avg)

[70.83333333 75.83333333 68.16666667 62.         72.33333333]
[74.8 63.4 69.4 76.2 72.  63.2]


## Task 4 — Who's on top? (10 min)

Using `np.argmax` / `np.argmin` (not manual comparison):
- Find the name of the **top-performing student** (highest `student_avg`).
- Find the name of the **hardest subject** (lowest `subject_avg`).

In [5]:
# Your code here
top= np.argmax(student_avg); students[top]
low= np.argmin(subject_avg); subjects[low]

print(top)
print(low)

1
5


## Task 5 — Pass/Fail matrix (10 min)

Using `np.where`, build a `status` array the same shape as `grades`, containing `'Pass'`
where the grade is ≥ 60 and `'Fail'` otherwise.

Then count how many total "Fail" entries exist in the whole matrix.

In [6]:
# Your code here

status = np.where(grades >= 60, 'Pass', 'Fail')
fail_count = np.sum(status == 'Fail')

print("Status matrix:\n", status)
print("Total fails:", fail_count)

Status matrix:
 [['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail']
 ['Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass']
 ['Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']
 ['Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass']
 ['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']]
Total fails: 8


## Task 6 — A new subject arrives (10 min)

A 6th subject, Music, is added. Generate a random grade for each of the 5 students
(same range as before) and add it as a **new column** to `grades` (use `np.append`,
`np.hstack`, or `np.column_stack` — your choice). Don't forget to also extend `subjects`
with `'Music'`.

Recompute `student_avg` with the new data.

In [10]:
# Your code here
g_mus = np.random.randint(40,101,size=(5,1))
grades = np.column_stack([grades,g_mus])

student_avg= grades.mean(axis=1)

student_avg

array([72.5  , 71.25 , 74.25 , 62.375, 79.   ])

## Task 7 — Rank the students (10 min)

Use `np.argsort` on the updated `student_avg` to print students **from highest to lowest**
average grade (name + average, formatted nicely).

> Hint: `np.argsort` sorts ascending by default — you'll need to reverse it.

In [15]:
# Your code here




p = np.argsort(student_avg)
print(p)
print(students[p],": ",student_avg[p])

[3 1 0 2 4]
['Kareem' 'Omar' 'Layla' 'Sara' 'Nour'] :  [62.375 71.25  72.5   74.25  79.   ]


## 🌟 Bonus — Normalize each student's grades (optional, ~10 min)

For each student (row), rescale their grades to a 0–1 range using min-max normalization:

`normalized = (grade - row_min) / (row_max - row_min)`

Do this **without a loop** — use `axis`-aware `.min(axis=...)` / `.max(axis=...)` together
with broadcasting (you'll need `keepdims=True` so the shapes line up for row-wise subtraction).

In [ ]:
# Your code here
row_min= grades.min(axis=1,keepdims=True)
row_max= grades.max(axis=1,keepdims=True)

normalized = (grades-row_min) / (row_max-row_min)
normalized

array([[0.66666667, 1.        , 0.41025641, 0.05128205, 0.76923077,
        0.        , 0.51282051, 0.79487179],
       [1.        , 0.18367347, 0.55102041, 0.93877551, 0.14285714,
        0.2244898 , 0.        , 0.26530612],
       [0.        , 0.        , 0.27659574, 0.89361702, 0.53191489,
        0.61702128, 1.        , 0.80851064],
       [0.36956522, 0.02173913, 0.32608696, 1.        , 0.        ,
        0.36956522, 0.32608696, 0.43478261],
       [0.68518519, 0.42592593, 0.57407407, 0.        , 0.98148148,
        0.25925926, 1.        , 0.96296296]])

---
### Submission checklist
- [ ] All 7 tasks run without errors, top to bottom
- [ ] Every array print is labeled (e.g. `print("Student averages:", ...)`) so it's readable
- [ ] No use of Python `for` loops for anything numpy could vectorize
- [ ] (Bonus) normalization attempted